# Generated by Django 6.0.3 on 2026-03-16 22:12

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('family', models.CharField(choices=[('STRINGS', 'Strings'), ('WOODWINDS', 'Woodwinds'), ('BRASS', 'Brass'), ('PERCUSSION', 'Percussion'), ('NULL', 'Null')], default='NULL')),
            ],
        ),
        migrations.CreateModel(
            name='Vibe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('picture', models.URLField(blank=True, null=True)),
                ('genre', models.ManyToManyField(to='chat.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Jam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('date_time', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('access', models.BooleanField(default=False, help_text='True means public, False means private')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_jams', to=settings.AUTH_USER_MODEL)),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.genre')),
                ('roles_needed', models.ManyToManyField(blank=True, to='chat.instrument')),
                ('spectators', models.ManyToManyField(blank=True, related_name='spectating_jams', to=settings.AUTH_USER_MODEL)),
                ('users_attending', models.ManyToManyField(blank=True, related_name='attending_jams', to=settings.AUTH_USER_MODEL)),
                ('vibe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.vibe')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participants', models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL)),
                ('jam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='chat.jam')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=15)),
                ('pfp', models.ImageField(blank=True, null=True, upload_to='')),
                ('about', models.TextField(blank=True, max_length=500, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MAN', 'Man'), ('WOMAN', 'Woman'), ('NON-BINARY', 'Nonbinary'), ('PREFER NOT TO SAY', 'Prefernottosay')], max_length=100)),
                ('spectator', models.BooleanField(default=False)),
                ('friends', models.ManyToManyField(blank=True, related_name='friends_of', to=settings.AUTH_USER_MODEL)),
                ('genres_liked', models.ManyToManyField(blank=True, related_name='profiles', to='chat.genre')),
                ('instruments_liked', models.ManyToManyField(blank=True, related_name='profiles', to='chat.instrument')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vibes_liked', models.ManyToManyField(blank=True, related_name='profiles', to='chat.vibe')),
            ],
        ),
    ]
