# Generated by Django 6.0.3 on 2026-04-08 02:43

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_post_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='jam',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='jam_images/'),
        ),
        migrations.AddField(
            model_name='jam',
            name='instruments_needed',
            field=models.ManyToManyField(blank=True, related_name='jams_needing_instrument', to='chat.instrument'),
        ),
        migrations.AddField(
            model_name='jam',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jam',
            name='jam_type',
            field=models.CharField(choices=[('OPEN JAM', 'Open Jam'), ('BAND PRACTICE', 'Band Practice'), ('SONGWRITING SESSION', 'Songwriting'), ('RECORDING SESSION', 'Recording'), ('LIVE PERFORMANCE', 'Live Performance'), ('WORKSHOP', 'Workshop')], default='OPEN JAM', max_length=50),
        ),
        migrations.AddField(
            model_name='jam',
            name='max_attendees',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jam',
            name='skill_level',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('PROFESSIONAL', 'Professional'), ('ALL LEVELS', 'All Levels')], default='ALL LEVELS', max_length=50),
        ),
        migrations.RemoveField(
            model_name='jam',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='jam',
            name='vibe',
        ),
        migrations.AlterField(
            model_name='profile',
            name='pfp',
            field=models.ImageField(blank=True, null=True, upload_to='pfp_images/'),
        ),
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_bands', to=settings.AUTH_USER_MODEL)),
                ('genres', models.ManyToManyField(blank=True, to='chat.genre')),
                ('members', models.ManyToManyField(related_name='bands', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BandmateListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('FILLED', 'Filled'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bandmate_listings', to=settings.AUTH_USER_MODEL)),
                ('band', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.band')),
                ('instrument_needed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.instrument')),
            ],
        ),
        migrations.AddField(
            model_name='jam',
            name='gear_needed',
            field=models.ManyToManyField(blank=True, related_name='jams_needing_gear', to='chat.gear'),
        ),
        migrations.AddField(
            model_name='jam',
            name='gear_provided',
            field=models.ManyToManyField(blank=True, related_name='jams_providing_gear', to='chat.gear'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('FRIEND_REQUEST', 'Friend Request'), ('FRIEND_ACCEPTED', 'Friend Accepted'), ('SHOW_REMINDER', 'Show Reminder'), ('BAND_CANDIDATE', 'Band Candidate'), ('BAND_UPDATE', 'Band Update')], max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='jam',
            name='roles_needed',
            field=models.ManyToManyField(blank=True, related_name='jams_needing_role', to='chat.role'),
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date_time', models.DateTimeField()),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('description', models.TextField(blank=True, null=True)),
                ('ticket_link', models.URLField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='show_images/')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_shows', to=settings.AUTH_USER_MODEL)),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.genre')),
                ('users_attending', models.ManyToManyField(blank=True, related_name='attending_shows', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='jam',
            name='genre',
            field=models.ManyToManyField(blank=True, to='chat.genre'),
        ),
        migrations.AddField(
            model_name='jam',
            name='vibe',
            field=models.ManyToManyField(blank=True, to='chat.vibe'),
        ),
        migrations.CreateModel(
            name='BandmateCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bandmate_applications', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='chat.bandmatelisting')),
            ],
            options={
                'unique_together': {('listing', 'user')},
            },
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DENIED', 'Denied')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_requests', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friend_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('from_user', 'to_user')},
            },
        ),
    ]
