# Generated by Django 6.0.3 on 2026-04-08 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_gear_role_alter_comment_options_jam_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='band',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='chat.band'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='chat.show'),
        ),
    ]
