# Generated by Django 6.0.3 on 2026-04-08 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_jam_location_profile_artists_liked_profile_bandcamp_and_more'),
        ('chat', '0004_conversation_band_conversation_show'),
    ]

    operations = [
    ]
