# Generated by Django 6.0.3 on 2026-04-09 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_conversation_band_conversation_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='genre',
        ),
        migrations.AddField(
            model_name='jam',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jam',
            name='location_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jam',
            name='location_guide',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jam',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='access',
            field=models.BooleanField(default=True, help_text='True means public, False means private'),
        ),
        migrations.AddField(
            model_name='show',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='genres',
            field=models.ManyToManyField(blank=True, to='chat.genre'),
        ),
        migrations.AddField(
            model_name='show',
            name='lineup',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='location_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='location_guide',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='max_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='ticket_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('FRIEND_REQUEST', 'Friend Request'), ('FRIEND_ACCEPTED', 'Friend Accepted'), ('SHOW_REMINDER', 'Show Reminder'), ('BAND_CANDIDATE', 'Band Candidate'), ('BAND_UPDATE', 'Band Update'), ('POST_LIKE', 'Post Like'), ('POST_COMMENT', 'Post Comment'), ('JAM_INVITE', 'Jam Invite')], max_length=20),
        ),
    ]
