# Generated by Django 6.0.3 on 2026-04-09 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_profile_artists_liked_profile_bandcamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skill_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('professional', 'Professional')], default='', max_length=20),
        ),
    ]
