# Generated by Django 6.0.3 on 2026-04-09 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_show_genre_jam_end_time_jam_location_address_and_more'),
        ('chat', '0006_profile_skill_level'),
    ]

    operations = [
    ]
