# Generated by Django 4.2.30 on 2026-04-09 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0007_merge_20260409_0145"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instrument",
            name="family",
            field=models.CharField(
                choices=[
                    ("STRINGS", "Strings"),
                    ("WOODWINDS", "Woodwinds"),
                    ("BRASS", "Brass"),
                    ("PERCUSSION", "Percussion"),
                    ("NULL", "Null"),
                ],
                default="NULL",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="JamAttendeeBringing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instruments_bringing", models.JSONField(blank=True, default=list)),
                ("roles_bringing", models.JSONField(blank=True, default=list)),
                ("gear_bringing", models.JSONField(blank=True, default=list)),
                (
                    "jam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendee_bringing",
                        to="chat.jam",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jam_bringing",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("jam", "user")},
            },
        ),
    ]
