# Generated by Django 6.0.3 on 2026-04-10 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_instrument_family_jamattendeebringing'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicSnip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('musicFile', models.FileField(blank=True, null=True, upload_to='audio_snips/')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_snips', to='chat.profile')),
            ],
        ),
    ]
