# Generated by Django 6.0.3 on 2026-04-12 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_musicsnip'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_banner',
            field=models.ImageField(blank=True, null=True, upload_to='profile_banners/'),
        ),
    ]
