# Generated by Django 4.2.30 — extended with RunSQL blocks for
# index, backfill, trigger, and recompute_unread RPC.
#
# AddField operations are standard Django DDL (ALTER TABLE ... ADD COLUMN).
# SeparateDatabaseAndState is used only for the id AlterField on
# ConversationParticipant, which is a Django state-only correction
# (the live column type is unchanged).
# RunSQL blocks run after all column additions in safe order:
#   1. index
#   2. backfill  (must precede trigger to avoid double-counting)
#   3. trigger
#   4. recompute_unread RPC

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0011_conversationparticipant_left_at"),
    ]

    operations = [

        # ── New columns: chat_conversation ────────────────────────────────────

        migrations.AddField(
            model_name="conversation",
            name="last_message_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conversation",
            name="last_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="chat.message",
            ),
        ),

        # ── New columns: chat_conversation_participants ───────────────────────

        migrations.AddField(
            model_name="conversationparticipant",
            name="unread_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="conversationparticipant",
            name="last_read_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="chat.message",
            ),
        ),
        migrations.AddField(
            model_name="conversationparticipant",
            name="last_read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),

        # ── State-only: pin ConversationParticipant.id to match existing DB ───
        # The live table already has an AutoField id column — no DDL needed.
        # This corrects Django's migration state to reflect the explicit model
        # definition without touching the database.

        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="conversationparticipant",
                    name="id",
                    field=models.AutoField(primary_key=True, serialize=False),
                ),
            ],
            database_operations=[],
        ),

        # ── Index: fast ORDER BY last_message_at DESC NULLS LAST ─────────────

        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS idx_chat_conversation_last_message_at
                ON chat_conversation (last_message_at DESC NULLS LAST);
            """,
            reverse_sql="DROP INDEX IF EXISTS idx_chat_conversation_last_message_at;",
        ),

        # ── Backfill ──────────────────────────────────────────────────────────
        # Populate summary columns from existing messages.
        # MUST run before the trigger — otherwise the trigger would increment
        # unread_count for rows that this backfill is about to reset to 0.

        migrations.RunSQL(
            sql="""
                UPDATE chat_conversation c
                SET last_message_at = m.timestamp,
                    last_message_id  = m.id
                FROM (
                    SELECT DISTINCT ON (conversation_id)
                           conversation_id, id, timestamp
                    FROM   chat_message
                    ORDER  BY conversation_id, timestamp DESC
                ) m
                WHERE c.id = m.conversation_id;

                UPDATE chat_conversation_participants
                SET unread_count = 0;
            """,
            reverse_sql="""
                UPDATE chat_conversation
                SET last_message_at = NULL,
                    last_message_id  = NULL;
            """,
        ),

        # ── Trigger: keep conversation summary + unread counts in sync ────────
        # Fires AFTER every INSERT on chat_message.
        #   • Updates last_message_at / last_message_id on the conversation row.
        #   • Increments unread_count for every active participant who is not
        #     the sender (left_at IS NULL, user_id != sender_id).

        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION update_conversation_on_message()
                RETURNS TRIGGER LANGUAGE plpgsql AS $$
                BEGIN
                    UPDATE chat_conversation
                    SET last_message_at = NEW.timestamp,
                        last_message_id  = NEW.id
                    WHERE id = NEW.conversation_id;

                    UPDATE chat_conversation_participants
                    SET unread_count = unread_count + 1
                    WHERE conversation_id = NEW.conversation_id
                      AND user_id         != NEW.sender_id
                      AND left_at         IS NULL;

                    RETURN NEW;
                END;
                $$;

                DROP TRIGGER IF EXISTS after_chat_message_insert ON chat_message;

                CREATE TRIGGER after_chat_message_insert
                AFTER INSERT ON chat_message
                FOR EACH ROW EXECUTE FUNCTION update_conversation_on_message();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS after_chat_message_insert ON chat_message;
                DROP FUNCTION IF EXISTS update_conversation_on_message();
            """,
        ),

        # ── recompute_unread RPC ──────────────────────────────────────────────
        # Corrects a stale unread_count after a user restores a hidden DM or
        # rejoins a jam chat (messages arrived while left_at was set and were
        # therefore skipped by the trigger).
        #
        # Uses the timestamp of the last-read message as the read boundary
        # (chat_message.id is UUID v4 — random, not orderable).
        # Falls back to counting all non-sender messages when no read pointer
        # exists (new participant or pointer was cleared by ON DELETE SET NULL).

        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION recompute_unread(
                    p_conversation_id UUID,
                    p_user_id         INTEGER
                ) RETURNS void LANGUAGE plpgsql AS $$
                DECLARE
                    v_last_read_ts TIMESTAMPTZ;
                BEGIN
                    SELECT m.timestamp
                    INTO   v_last_read_ts
                    FROM   chat_conversation_participants cp
                    LEFT   JOIN chat_message m ON m.id = cp.last_read_message_id
                    WHERE  cp.conversation_id = p_conversation_id
                      AND  cp.user_id         = p_user_id;

                    UPDATE chat_conversation_participants
                    SET unread_count = (
                        SELECT COUNT(*)
                        FROM   chat_message
                        WHERE  conversation_id = p_conversation_id
                          AND  sender_id        != p_user_id
                          AND  (v_last_read_ts IS NULL OR timestamp > v_last_read_ts)
                    )
                    WHERE conversation_id = p_conversation_id
                      AND user_id         = p_user_id;
                END;
                $$;
            """,
            reverse_sql="DROP FUNCTION IF EXISTS recompute_unread(UUID, INTEGER);",
        ),

    ]
