# Generated by Django 4.2.30 on 2026-04-15 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0015_jamrating"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="jam_rating",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feed_posts",
                to="chat.jamrating",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="post_type",
            field=models.CharField(
                choices=[
                    ("text", "text"),
                    ("photo", "photo"),
                    ("audio", "audio"),
                    ("review", "review"),
                ],
                default="text",
                max_length=20,
            ),
        ),
    ]
